#!/bin/sh
#
# Script to convert Reveal.js presentation to PDF, putting each fragment on a separate slide
#
# Author: Katie Miller (codemiller)

if [ -z "$1" ]; then 
    echo "Usage: revealation {reveal-slidedeck-url}"; 
    exit 1;
fi

URL=$1

command -v phantomjs >/dev/null 2>&1 || { echo >&2 "Revealation requires PhantomJS: please ensure it is installed and on your PATH"; exit 1; }
command -v convert >/dev/null 2>&1 || { echo >&2 "Revealation requires ImageMagick's convert program: please ensure it is installed and on your PATH"; exit 1; }

if [ ! -d "output" ]; then
    mkdir output
fi

cd output
phantomjs ../revealation.js $URL || { echo "Slide deck could not be crawled" ; exit 1; } 
convert *.png slides.pdf || { echo "Slide frames could not be converted to PDF" ; exit 1; } 

echo "Done! The slides are in output/slides.pdf"

